apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customdeployments.crd.emruz.com
spec:
  group: crd.emruz.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: customdeployments
    singular: customdeployments
    kind: CustomDeployment
    shortNames:
      - csd